// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c2cpush.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "C2Cpush.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - C2CpushRoot

@implementation C2CpushRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - C2CpushRoot_FileDescriptor

static GPBFileDescriptor *C2CpushRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol.protobuf"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - C2CPushRequest

@implementation C2CPushRequest

@dynamic from;
@dynamic content;
@dynamic msgid;
@dynamic timestamp;
@dynamic type;
@dynamic to;
@dynamic fromName;

typedef struct C2CPushRequest__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  NSString *from;
  NSString *content;
  NSString *to;
  NSString *fromName;
  int64_t msgid;
  int64_t timestamp;
} C2CPushRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "from",
        .dataTypeSpecific.className = NULL,
        .number = C2CPushRequest_FieldNumber_From,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C2CPushRequest__storage_, from),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = C2CPushRequest_FieldNumber_Content,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(C2CPushRequest__storage_, content),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "msgid",
        .dataTypeSpecific.className = NULL,
        .number = C2CPushRequest_FieldNumber_Msgid,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(C2CPushRequest__storage_, msgid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = C2CPushRequest_FieldNumber_Timestamp,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(C2CPushRequest__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = C2CPushRequest_FieldNumber_Type,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(C2CPushRequest__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "to",
        .dataTypeSpecific.className = NULL,
        .number = C2CPushRequest_FieldNumber_To,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(C2CPushRequest__storage_, to),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fromName",
        .dataTypeSpecific.className = NULL,
        .number = C2CPushRequest_FieldNumber_FromName,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(C2CPushRequest__storage_, fromName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C2CPushRequest class]
                                     rootClass:[C2CpushRoot class]
                                          file:C2CpushRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C2CPushRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\007\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - C2CPushResponse

@implementation C2CPushResponse

@dynamic msgid;

typedef struct C2CPushResponse__storage_ {
  uint32_t _has_storage_[1];
  int64_t msgid;
} C2CPushResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "msgid",
        .dataTypeSpecific.className = NULL,
        .number = C2CPushResponse_FieldNumber_Msgid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C2CPushResponse__storage_, msgid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C2CPushResponse class]
                                     rootClass:[C2CpushRoot class]
                                          file:C2CpushRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C2CPushResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
