// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c2csend.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "C2Csend.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - C2CsendRoot

@implementation C2CsendRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - C2CsendRoot_FileDescriptor

static GPBFileDescriptor *C2CsendRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol.protobuf"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - C2CSendRequest

@implementation C2CSendRequest

@dynamic from;
@dynamic to;
@dynamic content;
@dynamic type;
@dynamic toDomain;
@dynamic fromName;

typedef struct C2CSendRequest__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  int32_t toDomain;
  NSString *from;
  NSString *to;
  NSString *content;
  NSString *fromName;
} C2CSendRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "from",
        .dataTypeSpecific.className = NULL,
        .number = C2CSendRequest_FieldNumber_From,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C2CSendRequest__storage_, from),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "to",
        .dataTypeSpecific.className = NULL,
        .number = C2CSendRequest_FieldNumber_To,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(C2CSendRequest__storage_, to),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = C2CSendRequest_FieldNumber_Content,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(C2CSendRequest__storage_, content),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = C2CSendRequest_FieldNumber_Type,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(C2CSendRequest__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "toDomain",
        .dataTypeSpecific.className = NULL,
        .number = C2CSendRequest_FieldNumber_ToDomain,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(C2CSendRequest__storage_, toDomain),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "fromName",
        .dataTypeSpecific.className = NULL,
        .number = C2CSendRequest_FieldNumber_FromName,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(C2CSendRequest__storage_, fromName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C2CSendRequest class]
                                     rootClass:[C2CsendRoot class]
                                          file:C2CsendRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C2CSendRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\005\010\000\006\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - C2CSendResponse

@implementation C2CSendResponse

@dynamic msgid;
@dynamic timestamp;

typedef struct C2CSendResponse__storage_ {
  uint32_t _has_storage_[1];
  int64_t msgid;
  int64_t timestamp;
} C2CSendResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "msgid",
        .dataTypeSpecific.className = NULL,
        .number = C2CSendResponse_FieldNumber_Msgid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C2CSendResponse__storage_, msgid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = C2CSendResponse_FieldNumber_Timestamp,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(C2CSendResponse__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C2CSendResponse class]
                                     rootClass:[C2CsendRoot class]
                                          file:C2CsendRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C2CSendResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
